services:
  web:
    networks:
      - public
      - private
    container_name: rest_app
  db:
    networks:
      - private
  rabbitmq:
    networks:
      - public
  redis:
    networks:
      - public

networks:
  public:
    external: true
  private:
    external: false

